version: "3.6"

services:
  frontoffice:
    build:
      context: ./frontoffice
      dockerfile: Dockerfile
    container_name: frontoffice
    restart: always
    ports:
      - 3000:3000
    networks:
      - ecommerce-network

  backoffice:
    build:
      context: ./backoffice
      dockerfile: Dockerfile
    container_name: backoffice
    restart: always
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      - ecommerce-network

  postgres_db:
    image: postgresql:17-alpine
    container_name: postgres_db
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD_FILE: /run/secrets/db_secrets
    secrets:
      - db_secrets
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

secrets:
  db_secrets:
    file: ./secrets/db.text

networks:
  ecommerce-network:
    driver: bridge