version: "3.6"

services:
  server:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - ecommerce-private-network
      - ecommerce-public-network
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - frontoffice
      - backoffice
  frontoffice:
    build:
      context: ./frontoffice
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backoffice
    networks:
      - ecommerce-private-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 10s
      retries: 5

  backoffice:
    build:
      context: ./backoffice
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - ecommerce-private-network

  postgres_db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_secrets
    secrets:
      - db_secrets
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ecommerce-private-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:8-alpine
    restart: always
    command: sh -c "redis-server --requirepass $(cat /run/secrets/redis_secrets)"
    secrets:
      - redis_secrets
    networks:
      - ecommerce-private-network

volumes:
  db_data:

secrets:
  db_secrets:
    file: ./secrets/db.txt
  redis_secrets:
    file: ./secrets/redis.txt

networks:
  ecommerce-public-network:
    driver: bridge
  ecommerce-private-network:
    driver: bridge